services:
  - type: web
    name: flashcards-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri
      - key: PORT
        value: 8080
